AUDIT_FINDINGS = [
  {
    "nc_id": "NC #01",
    "clause_code": "IPSG.3(JCI)",
    "finding_text": "List of high alert medication was not available in Adult Emergency Department",
    "grade": "minor"
  },
  {
    "nc_id": "NC #02",
    "clause_code": "IPSG.3.1(JCI)",
    "finding_text": "List of lookalike and sound alike medication was not available in Adult Emergency Department",
    "grade": "minor"
  },
  {
    "nc_id": "NC #03",
    "clause_code": "IPSG.6.1(JCI)",
    "finding_text": "Patients in adult emergency were not screened for fall risk.",
    "grade": "major"
  },
  {
    "nc_id": "NC #04",
    "clause_code": "IPSG.6.1(JCI)",
    "finding_text": "There was no process for screening fall risk and implementation of measures and intervention to reduce risk of fall.",
    "grade": "major"
  },
  {
    "nc_id": "NC #05",
    "clause_code": "IPSG.6.1(JCI)",
    "finding_text": "Measures to reduce fall of risks were not implemented. Description is documented below: 1. Stretchers had no side rails. 2. Porters were not available to attend patient at the entrance of ER to transfer them on beds/wheel chairs. It has been observed that attendants of patients shift their patient on stretchers and wheel chair by themselves.",
    "grade": "major"
  },
  {
    "nc_id": "NC #06",
    "clause_code": "ACC.2(JCI)",
    "finding_text": "It has observed that there was no traceability of flow of patients from Emergency Department to diagnostic Imaging areas. Emergency Department have no documented information that when patient was move from ER to other location.",
    "grade": "moderate"
  },
  {
    "nc_id": "NC #07",
    "clause_code": "8.1.3 (SHCC)",
    "finding_text": "There was no singed agreement of Emergency Department (adult) with other Emergency units for close professional links. However there was al WhatsApp group of all Emergency Departments situated in the Karachi for patient related communication.",
    "grade": "major"
  },
  {
    "nc_id": "NC #08",
    "clause_code": "8.1.5 SHCC",
    "finding_text": "Data of repeat visits of patient was not maintained by the department.",
    "grade": "minor"
  },
  {
    "nc_id": "NC #09",
    "clause_code": "8.2.12 SHCC",
    "finding_text": "There was no defined procedure for consult generated by Emergency Department for the specialist care. Moreover there was no mechanism to identify the nature of consult (urgent/routine). Time frame to entertain the consult was also not defined.",
    "grade": "major"
  },
    {
    "nc_id": "NC #10",
    "clause_code": "5.3.5 SHCC",
    "finding_text": "At the time of assessment, doctor’s asked the values and beliefs of patients;, however, documentation of the same was not found in the medical record.",
    "grade": "minor"
  },
    {
    "nc_id": "NC #11",
    "clause_code": "8.3.9 SHCC, COP.3.3 JCI",
    "finding_text": """Defebrillator and crash cart was not available in the following areas of emergency;
    1. Defibrillator and Crash Cart - SN treatment bay
    2. Defibrillator - Fast  running bay""",
    "grade": "major"
  },
   {
    "nc_id": "NC #12",
    "clause_code": "8.3.11 SHCC",
    "finding_text": "In SN treatment bay curtains were not available with patient beds.",
    "grade": "major"
  },
    
   {
    "nc_id": "NC #13",
    "clause_code": "8.3.14 SHCC",
    "finding_text": "Toilet facility was available for males and disabled patients., However, female toilet facility was not available in main Adult Emergency. Moreover commode was not present in toilet of disable personnel.",
    "grade": "major"
  },
    {
    "nc_id": "NC #14",
    "clause_code": "PCC.1.4 JCI",
    "finding_text": "Patients were protected from physical assualt, however there was no mechanism to identify patient at risk of vulnerabilities.",
    "grade": "moderate"
  },
    {
    "nc_id": "NC #15",
    "clause_code": "6.1.2 SHCC",
    "finding_text": "Only 3 beds and 4 wheel chairs were available at the entrance of emergency department, which were not enough to cater the load of patients. Upon verification it has been told by the representative (CSM & Nursing) that these wheel chairs and beds were not belong to ER inventory and most of time ER  was running of shortage.",
    "grade": "moderate"
  },
  {
    "nc_id": "NC #16",
    "clause_code": "6.3.5 SHCC, AOP.1.1 JCI",
    "finding_text": "Spiritual, social and economic factors were not included in the initial assessment of patients.",
    "grade": "minor",
  },
    {
    "nc_id": "NC #17",
    "clause_code": "6.7.5 SHCC, ACC.4.1 JCI",
    "finding_text": "Discharge slip was provided to patient on which treatment was documented, however condition at discharge and name of attending practitioner was not documented on discharge slip.",
    "grade": "moderate",
  },

]

{
    "nc_id": "NC #18",
    "clause_code": "WHO",
    "finding_text": "Emergency exit of see and treat area was open. Signage of emergency exit was also not present. Moreover key to open emergency exit was also not available in see and treat area.",
    "grade": "major",
},